# -*- coding: utf-8 -*-
"""mde_arkit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_1olA7UuP4wtVq3OVcxJY-WPUoyaRHl
"""

import numpy as np
import cv2
import gdown
import os
import shutil
import subprocess
# import zipfile
# import requests

from pathlib import Path
# from PIL import Image
from tqdm.notebook import tqdm

import matplotlib.pyplot as plt
# import seaborn as sns
# import kagglehub
import numpy as np
import pandas as pd
import torch
# from torch.utils.data import Dataset, DataLoader
# from transformers import pipeline

# from sklearn.linear_model import Ridge
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.transforms import functional
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import v2
from torchvision import transforms


print('ok')

def print_dir_struct(path: Path, max_depth=3, max_cnt=5, prefix="", cur_depth=0):
    items = os.listdir(path)
    if (len(items) > max_cnt):
        items = items[:max_cnt] + [". . ."]
    for i, item in enumerate(items):
        custom_prefix = "└── " if i == len(items) - 1 else "├── "
        print(prefix, custom_prefix, item)
        if cur_depth < max_depth and os.path.isdir(os.path.join(path, item)) and item != ". . .":
            custom_prefix = '    ' if i == len(items) - 1 else ' │   '
            print_dir_struct(os.path.join(path, item), max_depth, max_cnt, prefix + custom_prefix, cur_depth + 1)

def show_res(rgb, lr_depth, hr_depth, depth, name='tmp'):
    fig, ax = plt.subplots(2, 2, figsize=(15, 10))
    hr_depth[hr_depth == 0] = np.nan
    data = [rgb, lr_depth, hr_depth, depth]
    titles = ["RGB", "LR Depth", "HR Depth", "Predicted Depth"]
    for i in range(4):
        im = ax[i // 2, i % 2].imshow(data[i])
        ax[i // 2, i % 2].set_title(titles[i])
        fig.colorbar(im, ax=ax[i // 2, i % 2])
    plt.tight_layout()
    plt.savefig(name+".png")
    plt.close(fig)
    # plt.show()

print(f"CUDA Available: {torch.cuda.is_available()}")
print(f"GPU Name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")
DEVICE = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'

"""### ARKitScenes

!git clone https://github.com/apple/ARKitScenes.git

MAX DEPTH LR = 5 meters !
"""

def check_dir_for_cleanup(path='.', max_gb=10.0, target_gb=0.75):
    MAX_BYTES = max_gb * (1024**3)
    TARGET_BYTES = target_gb * (1024**3)
    def get_dir_size_fast(path):
        total = 0
        with os.scandir(path) as it:
            for entry in it:
                if entry.is_file():
                    total += entry.stat().st_size
                elif entry.is_dir():
                    total += get_dir_size_fast(entry.path)
        return total

    with os.scandir(path) as it:
        files = [entry for entry in it]
    files.sort(key=lambda x: x.stat().st_mtime)
    files_size = np.array([file.stat().st_size if file.is_file() else get_dir_size_fast(file.path) for file in files])
    if np.sum(files_size) > MAX_BYTES:

        deleted = 0
        for file, size in zip(files, files_size):
            if file.is_file():
                os.remove(file.path)
            elif file.is_dir():
                shutil.rmtree(file.path)
            deleted += size
            if deleted >= TARGET_BYTES:
                return 0
    return 0

def get_sorted_dirs(path='.'):
    with os.scandir(path) as it:
        dirs = [entry for entry in it if entry.is_dir()]
    dirs.sort(key=lambda x: x.stat().st_mtime)
    return dirs

class ARKitDataset:
    def __init__(self,
    download_dir=os.getcwd()+'/datasets/arkit-scenes',
    git_repository_path=os.getcwd()+'/ARKitScenes',
    dataset='upsampling',
    split='Training',
    silent=False):
        self.download_dir = download_dir
        self.git_repository_path = git_repository_path
        self.dataset = dataset
        self.split = split
        self.silent = silent
        if not os.path.exists(download_dir):
            os.makedirs(download_dir)
        train_val_splits_df = pd.read_csv(git_repository_path + "/depth_upsampling/upsampling_train_val_splits.csv")
        self.video_ids = train_val_splits_df[train_val_splits_df['fold'] == split]['video_id'].to_list()
        self.data_dir = os.path.join(self.download_dir, "upsampling", self.split)
        if not os.path.exists(self.data_dir):
            os.makedirs(self.data_dir)

    def run_loading_data_script(
            self,
    csv_path=None,
    video_ids=None,
    ):
        cmd = [
            'python',
            os.path.join(self.git_repository_path, 'download_data.py'),
            self.dataset,
            '--split', self.split,
            '--download_dir', self.download_dir
        ]
        if (csv_path is not None):
            cmd += ['--video_id_csv'] + [csv_path]
        elif (video_ids is not None):
            cmd += ['--video_id'] + list(map(str, video_ids))
            video_paths = list()
            for video_id in video_ids:
                video_path = os.path.join(self.download_dir, self.dataset, self.split, video_id)
                video_paths.append(video_path)
        result = subprocess.run(cmd, capture_output=True, text=True)
        if (not self.silent): print(result.stdout)
        if result.stderr:
            print("Errors:", result.stderr)
        return self.download_dir

    def image_seq(self, n=None, skip_to=None):
        scene_count = len(self.video_ids)
        img_returned = 0
        img_limit = False
        start = 0 if skip_to is None else self.video_ids.index(skip_to)
        for i in range(start, scene_count):
            # check if space is avaible
            # check_dir_for_cleanup(self.data_dir)

            self.run_loading_data_script(video_ids=[str(self.video_ids[i])])

            video_dir = os.path.join(self.data_dir, str(self.video_ids[i]))
            hr_depth_dir = os.path.join(video_dir, "highres_depth")
            lr_depth_dir = os.path.join(video_dir, "lowres_depth")
            rgb_dir = os.path.join(video_dir, "wide")
            for filename in os.listdir(hr_depth_dir):
                hr_depth_np = cv2.imread(os.path.join(hr_depth_dir, filename), cv2.IMREAD_UNCHANGED)
                lr_depth_np = cv2.imread(os.path.join(lr_depth_dir, filename), cv2.IMREAD_UNCHANGED)

                # Convert to Torch Tensors and Scale (keeping on GPU in float16)
                hr_depth = torch.from_numpy(hr_depth_np.astype('float32')).to(DEVICE) / 1000.0
                lr_depth = torch.from_numpy(lr_depth_np.astype('float32')).to(DEVICE) / 1000.0

                # 2. Load and Prepare RGB
                rgb_np = cv2.imread(os.path.join(rgb_dir, filename)) # BGR by default
                rgb = cv2.cvtColor(rgb_np, cv2.COLOR_BGR2RGB)     # Convert to RGB

                # Convert to [C, H, W] format and Scale to 0-1
                # rgb = torch.from_numpy(rgb_np).to(DEVICE).permute(2, 0, 1).float() / 255.0

                if self.video_ids[i] == 48458647: # damaged scene
                    hr_depth = torch.rot90(hr_depth, k=-1, dims=(0, 1))
                    lr_depth = torch.rot90(lr_depth, k=-1, dims=(0, 1))


                yield rgb, lr_depth, hr_depth
                img_returned += 1
                if (n is not None) and (img_returned >= n):
                    img_limit = True
                    break
            if img_limit:
                break

    # def image_seq_scene(self, video_id = 48458647):
    #     # check if space is avaible
    #     check_dir_for_cleanup(self.data_dir)
    #     print(video_id)
    #     self.run_loading_data_script(video_ids=[str(video_id)])
    #     video_dir = os.path.join(self.data_dir, str(video_id))
    #     hr_depth_dir = os.path.join(video_dir, "highres_depth")
    #     lr_depth_dir = os.path.join(video_dir, "lowres_depth")
    #     rgb_dir = os.path.join(video_dir, "wide")
    #     for filename in os.listdir(hr_depth_dir):
    #         hr_depth = plt.imread(os.path.join(hr_depth_dir, filename))
    #         lr_depth = plt.imread(os.path.join(lr_depth_dir, filename))
    #         rgb = plt.imread(os.path.join(rgb_dir, filename))

    #         if video_id == 48458647: # damaged scene
    #             hr_depth = np.rot90(hr_depth, k=-1)
    #             lr_depth = np.rot90(lr_depth, k=-1)

    #         yield rgb, lr_depth, hr_depth

# def arkit_collect_paths(dataset_dir, split="train"):
#     '''
#     dataset_dir: path to directory with NYUv2 Dataset with structure
#         ARKitScenes/upsampling
#         ├── Training/
#         │   ├── 41048190/
#         │   │   ├── confidence
#         │   │   ├── highres_depth
#         │   │   ├── lowres_depth
#         │   │   └── wide
#         │   └── ...
#         └── Validation/
#             ├── 41069021/
#             │   ├── confidence
#             │   ├── highres_depth
#             │   ├── lowres_depth
#             │   └── wide
#             └── ...
#     split: 'train' or 'test'
#     '''

#     fold = "upsampling/Training" if split == "train" else "upsampling/Validation"
#     train_dir = os.path.join(dataset_dir, fold)
#     dirs = os.listdir(train_dir)

#     paths = []
#     for video_id in dirs:
#         if not os.path.isdir(os.path.join(train_dir, str(video_id))): continue
#         wide_dir = os.path.join(train_dir, str(video_id), "wide")
#         for file in os.listdir(wide_dir):
#             paths.append([
#                 os.path.join(fold, str(video_id), "wide", file),
#                 os.path.join(fold, str(video_id), "confidence", file),
#                 os.path.join(fold, str(video_id), "highres_depth", file),
#                 os.path.join(fold, str(video_id), "lowres_depth", file)
#             ])
#     paths = pd.DataFrame(paths, columns=['rgb_path', 'conf_path', 'hr_depth_path', 'lr_depth_path'])
#     return paths

# class ArkitDataset(Dataset):
#     '''
#     Dataset class for ARKitScenes
#     '''

#     def __init__(self,
#                 dataset_dir,
#                 split='train',
#                 csv_path=None,
#                 save=False,
#                 rgb_transform=None,
#                 lr_depth_transform=None,
#                 hr_depth_transform=None,
#                 conf_transform=None):
#         super().__init__()
#         self.dataset_dir = dataset_dir
#         self.split = split
#         self.rgb_transform = rgb_transform
#         self.lr_depth_transform = lr_depth_transform
#         self.hr_depth_transform = hr_depth_transform
#         self.conf_transform = conf_transform

#         if csv_path is not None and os.path.exists(csv_path):
#             self.paths = pd.read_csv(csv_path)
#         else:
#             self.paths = arkit_collect_paths(self.dataset_dir, split=split)
#             if (save and csv_path is not None):
#                 self.paths.to_csv(csv_path, index=False)

#     def __getitem__(self, idx):
#         row = self.paths.iloc[idx]
#         rgb = Image.open(os.path.join(self.dataset_dir, row['rgb_path']))
#         lr_depth = Image.open(os.path.join(self.dataset_dir, row['lr_depth_path']))
#         hr_depth = Image.open(os.path.join(self.dataset_dir, row['hr_depth_path']))
#         conf = Image.open(os.path.join(self.dataset_dir, row['conf_path']))

#         if self.rgb_transform is not None:
#             rgb = self.rgb_transform(rgb)
#         if self.lr_depth_transform is not None:
#             lr_depth = self.lr_depth_transform(lr_depth)
#         if self.hr_depth_transform is not None:
#             hr_depth = self.hr_depth_transform(hr_depth)
#         if self.conf_transform is not None:
#             conf = self.conf_transform(conf)

#         sample = {
#             'rgb': rgb,
#             'lr_depth': lr_depth,
#             'hr_depth': hr_depth,
#             'conf': conf,
#             'rgb_path': row['rgb_path'],
#             'lr_depth_path': row['lr_depth_path'],
#             'hr_depth_path': row['hr_depth_path'],
#             'conf_path': row['conf_path']
#         }

#         return sample

#     def __len__(self):
#         return self.paths.shape[0]

# dataset = ARKitDataset(split='Validation')

# for rgb, lr_depth, hr_depth in tqdm(dataset.image_seq(1)):
#     show_res(rgb, lr_depth, hr_depth, hr_depth)

"""### Depth Anything v2"""

import cv2
import torch
import sys
import importlib.util


# def load_model_class(model_path, class_name="DepthAnythingV2"):
#     # Construct the absolute path to the dpt.py file
#     file_path = os.path.join(repo_path, "depth_anything_v2/dpt.py")

#     spec = importlib.util.spec_from_file_location(
#         "temp_module",
#         os.path.join(model_path, "depth_anything_v2/dpt.py")
#     )
#     module = importlib.util.module_from_spec(spec)
#     # Add the path to sys.path temporarily so internal relative imports work
#     sys.path.insert(0, model_path)
#     spec.loader.exec_module(module)
#     sys.path.pop(0)
#     return getattr(module, class_name)


model_configs = {
    'vits': {'encoder': 'vits', 'features': 64, 'out_channels': [48, 96, 192, 384]},
    'vitb': {'encoder': 'vitb', 'features': 128, 'out_channels': [96, 192, 384, 768]},
    'vitl': {'encoder': 'vitl', 'features': 256, 'out_channels': [256, 512, 1024, 1024]},
    'vitg': {'encoder': 'vitg', 'features': 384, 'out_channels': [1536, 1536, 1536, 1536]}
}

encoder = 'vits' # or 'vits', 'vitb', 'vitg'
dataset = 'hypersim' # 'hypersim' for indoor model, 'vkitti' for outdoor model
max_depth = 20



repo_path = os.path.join(os.getcwd(), 'Depth-Anything-V2/')
sys.path.append(repo_path)
from depth_anything_v2.dpt import DepthAnythingV2 as RelativeModel


model = RelativeModel(**model_configs[encoder])
model.load_state_dict(torch.load(f'./Depth-Anything-V2/checkpoints/depth_anything_v2_{encoder}.pth', map_location='cpu'))
model = model.to(DEVICE).eval()


# model = MetricModel(**{**model_configs[encoder], 'max_depth': max_depth})
# model.load_state_dict(torch.load(f'Depth-Anything-V2/checkpoints/depth_anything_v2_metric_{dataset}_{encoder}.pth', map_location='cpu'))
# model = model_metric.to(DEVICE).eval()

# MAX_DEPTH = 5 or 70 meters?

import torch.nn.functional as F

def predict_(depth, lr_depth):
    target_h, target_w = depth.shape[-2:]
    # 2. Reshape to 4D: [Batch=1, Channel=1, H_lr, W_lr]
    lr_depth_4d = lr_depth.unsqueeze(0).unsqueeze(0)
    interpolated_depth = F.interpolate(
        lr_depth_4d,
        size=(target_h, target_w),
        mode='bilinear',
        align_corners=False
    ).squeeze()
    return interpolated_depth

def predict0(depth, lr_depth):
    return depth

def predict1_torch(depth, lr_depth):
    # depth: [H, W], lr_depth: [H_lr, W_lr]
    # Resize depth to match lr_depth target size
    pred_resized = F.interpolate(depth.unsqueeze(0).unsqueeze(0),
                                 size=lr_depth.shape,
                                 mode='bilinear',
                                 align_corners=False).squeeze()

    x = pred_resized.flatten()
    y = lr_depth.flatten()

    # Create Design Matrix [x, 1]
    A = torch.stack([x, torch.ones_like(x)], dim=1)

    # Solve least squares: Ax = y
    # result[0] contains [s, t]
    sol = torch.linalg.lstsq(A, y).solution
    s, t = sol[0], sol[1]

    return s * depth + t

def predict2_torch(depth, lr_depth):
    max_depth = lr_depth.max()
    pred_resized = F.interpolate(depth.unsqueeze(0).unsqueeze(0),
                                 size=lr_depth.shape,
                                 mode='bilinear',
                                 align_corners=False).squeeze()

    x = pred_resized.flatten()
    y = 1.0 / lr_depth.flatten()

    A = torch.stack([x, torch.ones_like(x)], dim=1)
    sol = torch.linalg.lstsq(A, y).solution
    s, t = sol[0], sol[1]

    d = s * depth + t
    # Safe reciprocal to avoid div by zero
    metric_map = torch.where(d != 0, 1.0 / d, max_depth)
    return metric_map

def predict3_torch(depth, lr_depth):
    max_depth = lr_depth.max()
    lr_d = 1.0 / lr_depth

    # Center depth by median
    depth_centered = depth - torch.median(depth)

    # Center target inverse depth by median
    t = torch.median(lr_d)
    lr_d_centered = lr_d - t

    # Scale alignment using Mean Absolute Deviation
    depth_scale = torch.mean(torch.abs(depth_centered))
    lr_d_scale = torch.mean(torch.abs(lr_d_centered))

    s = lr_d_scale / (depth_scale + 1e-8) # avoid div by zero

    d = (s * depth_centered + t)
    metric_map = torch.where(d != 0, 1.0 / d, max_depth)
    return metric_map

"""### Metrics"""

def eval_depth(pred, target):
    assert pred.shape == target.shape

    mask = target != 0

    thresh = torch.max((target[mask] / pred[mask] ), (pred[mask]  / target[mask] ))

    d1 = (thresh < 1.25).float().mean()
    d2 = (thresh < 1.25**2).float().mean()
    d3 = (thresh < 1.25**3).float().mean()

    diff = pred[mask]  - target[mask]

    pred_safe = torch.clamp(pred[mask], min=1e-3)
    target_safe = torch.clamp(target[mask], min=1e-3)
    diff_log = torch.log(pred_safe) - torch.log(target_safe)

    # diff_log = torch.log(pred[mask]) - torch.log(target[mask])

    abs_rel = torch.mean(torch.abs(diff) / target[mask])

    rmse = torch.sqrt(torch.mean(torch.pow(diff, 2)))
    mae = torch.mean(torch.abs(diff))

    silog = torch.sqrt(torch.pow(diff_log, 2).mean() - 0.5 * torch.pow(diff_log.mean(), 2))

    return {
        'd1': d1.item(),
        'd2': d2.item(),
        'd3': d3.item(),
        'abs_rel': abs_rel.item(),
        'rmse': rmse.item(),
        'mae': mae.item(),
        'silog': silog.item()
    }
# def eval_depth_numpy(pred, target):
#     d1 = torch.from_numpy(pred)
    # d2 = torch.from_numpy(target)
    # return eval_depth(d1, d2)

# def show_res(rgb, lr_depth, hr_depth, depth):
#     fig, ax = plt.subplots(2, 2, figsize=(15, 10))
#     data = [rgb, lr_depth, hr_depth, depth]
#     titles = ["RGB", "LR Depth", "HR Depth", "Predicted Depth"]
#     for i in range(4):
#         im = ax[i // 2, i % 2].imshow(data[i])
#         plt.colorbar(im, ax=ax[i // 2, i % 2], location='right')
#         ax[i // 2, i % 2].set_title(titles[i])
#     plt.savefig("tmp.png")
#     plt.show()

# dataset = ARKitDataset(split='Validation')
# for rgb, lr_depth, hr_depth in tqdm(dataset.image_seq(1, skip_to=42446522)):
#     show_res(rgb, lr_depth, hr_depth, lr_depth)
#     print(np.max(hr_depth))

dataset = ARKitDataset(split='Validation')


methods_names = [ 'interpolate', 'raw', 'linalg of depth', 'linalg of disparity', 's and t out of disparity']
methods = { 'interpolate' : predict_, 'raw' : predict0, 'linalg of depth' : predict1_torch, 'linalg of disparity' : predict2_torch, 's and t out of disparity' : predict3_torch}

stats = {
    m: {
        'd1': [], 'd2': [], 'd3': [],
        'abs_rel': [],
        'rmse': [], 'mae': [], 'silog': []
    } for m in methods_names
}

img_count = 0

for rgb, lr_depth, hr_depth in tqdm(dataset.image_seq()):

    with torch.no_grad():
        image, (h, w) = model.image2tensor(rgb, 518)
        depth = model.forward(image)
        depth = F.interpolate(depth[:, None], (h, w), mode="bilinear", align_corners=True)[0, 0]

    for m in methods_names:
        pred = methods[m](depth, lr_depth)
        predictions = eval_depth(pred, hr_depth)
        if img_count % 100 == 0:
            show_res(rgb, lr_depth.detach().cpu().numpy(), hr_depth.detach().cpu().numpy(), pred.detach().cpu().numpy(), m + str(img_count))
        if predictions is not None:
            for key in predictions:
                stats[m][key].append(predictions[key])

    img_count += 1



final_results = {}
for m in methods_names:
    # Average each metric list into a single value
    final_results[m] = {key: np.mean(val) for key, val in stats[m].items()}

# Convert to DataFrame for a clean, readable table
df = pd.DataFrame(final_results).T
print(df)


detailed_data = []

for method in methods_names:
    for i in range(len(stats[method]['rmse'])):
        row = { 'method': method, 'image_idx': i }
        # Add all metrics for this specific image
        for metric in stats[method]:
            row[metric] = stats[method][metric][i]
        detailed_data.append(row)

# 2. Create DataFrame and Save
df_detailed = pd.DataFrame(detailed_data)
df_detailed.to_csv("mde_full_results.csv", index=False)
print("Detailed per-image results saved!")


# print(results2)
# print(results3)

print('img count = ', img_count)

"""5529/5599

48458647 - испорчен
"""
